# Generated by Django 4.1.5 on 2023-01-10 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candle_name', models.CharField(max_length=20)),
                ('status', models.BooleanField()),
                ('total_time_lit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Candle_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_time', models.DateTimeField()),
                ('extinguish_time', models.DateTimeField()),
                ('candle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candletime.candle')),
            ],
        ),
    ]
