# Generated by Django 4.1.5 on 2023-01-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candletime', '0002_alter_candle_total_time_lit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle_detail',
            name='extinguish_time',
            field=models.DateTimeField(null=True),
        ),
    ]
